name: Build PRoot for Android

on:
  workflow_dispatch:

env:
  PREFIX: ./dependencies/install
  DWNLD: ./dependencies/download
jobs:
  build:
    strategy:
      matrix:
        arch: [aarch64, x86_64]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r28c

      - name: Download dependencies
        run: |
          sudo apt-get install -y autoconf automake libtool pkg-config

          mkdir -p ${{ env.PREFIX }}
          mkdir -p ${{ env.DWNLD }}
          cd ${{ env.DWNLD }}

          # libarchive
          git clone https://github.com/libarchive/libarchive.git -b v3.8.1
          git clone https://github.com/madler/zlib.git -b v1.3.1

          # talloc
          git clone https://gitlab.com/samba-team/samba.git -b talloc-2.4.3
          
          # uthash
          git clone https://github.com/troydhanson/uthash.git -b v2.3.0

          git clone https://github.com/proot-me/proot.git

      - name: Build dependencies
        env:
          ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
          ARCH: ${{ matrix.arch }}
          PREFIX: ${{ env.PREFIX }}
          DWNLD: ${{ env.DWNLD }}
        run: |

          export TOOLCHAIN=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64
          export TARGET=$ARCH-linux-android
          export API=24

          export DWNLD=$(realpath $DWNLD)
          export PREFIX=$(realpath $PREFIX)

          export AR=$TOOLCHAIN/bin/llvm-ar
          export CC="$TOOLCHAIN/bin/clang --target=$TARGET$API"
          export AS=$CC
          export CXX="$TOOLCHAIN/bin/clang++ --target=$TARGET$API"
          export LD=$TOOLCHAIN/bin/ld
          export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
          export STRIP=$TOOLCHAIN/bin/llvm-strip

          export CFLAGS="-I$PREFIX/include"
          export LDFLAGS="-L$PREFIX/lib"

          ln -sf ${TOOLCHAIN}/bin/${TARGET}${API}-clang ${TOOLCHAIN}/bin/${TARGET}${API}-gcc
          ln -sf ${TOOLCHAIN}/bin/${TARGET}${API}-clang++ ${TOOLCHAIN}/bin/${TARGET}${API}-g++
          ln -sf ${TOOLCHAIN}/bin/llvm-strip ${TOOLCHAIN}/bin/${TARGET}${API}-strip

          # talloc
          export B_LDFLAGS=$LDFLAGS
          export B_CFLAGS=$CFLAGS
          export LDFLAGS="--sysroot=$TOOLCHAIN/sysroot -L$PREFIX/lib"
          export CFLAGS="--sysroot=$TOOLCHAIN/sysroot -I$PREFIX/include"
          cd $DWNLD/samba/lib/talloc
          ./configure --host $TARGET --prefix=$PREFIX --cross-compile
          make
          make install
          export LDFLAGS=$B_LDFLAGS
          export CFLAGS=$B_CFLAGS

          # libarchive
          cd $DWNLD/zlib
          ./configure --prefix=$PREFIX --static
          make
          make install

          cd $DWNLD/libarchive
          for f in libarchive/archive.h libarchive/archive_entry.h; do # patch to remove android_lf.h include
              sed -i 's|#include "android_lf.h"|/* removed android_lf.h */|' "$f"
          done
          sh ./build/autogen.sh
          ./configure --host=$TARGET --prefix=$PREFIX \
            --without-xml2 \
            --without-openssl \
            --without-nettle \
            --without-expat \
            --without-iconv \
            --without-bz2lib \
            --without-lzma \
            --without-lz4 \
            --without-zstd \
            --without-xattr \
            --without-acl \
            --disable-shared \
            --enable-static
          make
          make install
          cd ..

          # uthash
          cd $DWNLD/uthash
          mkdir -p $PREFIX/include/
          cp -r src/* $PREFIX/include/


          export CROSS_COMPILE="${TOOLCHAIN}/bin/${TARGET}${API}-"

          cd $DWNLD/proot/src
          make loader.elf loader-m32.elf build.h
          make proot care

          mkdir -p ../../dist/$ARCH
          cp proot ../../dist/$ARCH/
          cp care ../../dist/$ARCH/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proot-android-${{ matrix.arch }}
          path: dist/${{ matrix.arch }}/
