name: Build PRoot for Android

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: [aarch64, x86_64]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r28c

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13.7'

      - name: Set up QEMU
        if: matrix.arch == 'aarch64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Ubuntu setup
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl jq autoconf automake libtool pkg-config qemu-user-static unzip
          git config --global advice.detachedHead false

      - name: Download all sources
        run: |
          chmod +x ./scripts/download_all.sh
          ./scripts/download_all.sh

      - name: Build all packages
        run: |
          chmod +x ./scripts/build_all.sh ./scripts/build_one.sh
          export ARCH=${{ matrix.arch }}
          ./scripts/build_all.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proot-android-${{ matrix.arch }}
          path: dist/${{ matrix.arch }}/
