name: Build PRoot for Android on android

on:
  workflow_dispatch:

env:
  PREFIX: /tmp/deps/installed

jobs:
  build:
    strategy:
      matrix:
        arch: [arm64, x86_64]

    runs-on: ubuntu-latest
    container:
      image: cimg/android:2025.09.1-ndk
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download dependencies
        run: |
          mkdir -p /tmp/deps/installed
          cd /tmp/deps
          # libarchive
          git clone https://github.com/libarchive/libarchive.git -b v3.8.1
          # talloc
          curl -LO https://www.samba.org/ftp/talloc/talloc-2.4.3.tar.gz
          tar xzf talloc-2.4.3.tar.gz
          mv talloc-2.4.3 talloc
          # uthash
          git clone https://github.com/troydhanson/uthash.git -b v2.3.0

          git clone https://github.com/proot-me/proot.git

      - name: Build dependencies
        run: |
          # libarchive
          cd /tmp/deps/libarchive
          ./build/autogen.sh
          ./configure --prefix=${{ env.PREFIX }} \
            --enable-static \
            --disable-shared \
            --without-lzma \
            --without-bz2
          make -j$(nproc)
          make install

          # talloc
          cd /tmp/deps/talloc
          ./configure --prefix=${{ env.PREFIX }} \
            --enable-static \
            --disable-shared
          make -j$(nproc)
          make install

          # uthash
          cd /tmp/deps/uthash
          mkdir -p ${{ env.PREFIX }}/include/
          cp -r src/* ${{ env.PREFIX }}/include/

      - name: Build PRoot
        env:
          ARCH: ${{ matrix.arch }}
          PREFIX: ${{ env.PREFIX }}
        run: |
          cd proot/src

          # Ustal target
          case "${ARCH}" in
            arm64)
              TARGET=aarch64-linux-android
              ;;
            x86_64)
              TARGET=x86_64-linux-android
              ;;
          esac

          # Symlink tools
          # ln -sf ${TOOLCHAIN}/${TARGET}${API}-clang  ${TOOLCHAIN}/${TARGET}${API}-gcc
          # ln -sf ${TOOLCHAIN}/${TARGET}${API}-clang++ ${TOOLCHAIN}/${TARGET}${API}-g++
          # ln -sf ${TOOLCHAIN}/llvm-strip ${TOOLCHAIN}/${TARGET}${API}-strip
          # export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH

          export CFLAGS="-I${PREFIX}/include"
          export LDFLAGS="-L${PREFIX}/lib -larchive -ltalloc"

          make loader.elf loader-m32.elf build.h
          make proot care

          mkdir -p ../../dist/$ARCH
          cp proot ../../dist/$ARCH/
          cp care ../../dist/$ARCH/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proot-android-${{ matrix.arch }}
          path: dist/${{ matrix.arch }}/
