name: Build PRoot for Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [arm64-v8a, x86_64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Android NDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'ndk;28.2.13676358'

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y make git libtalloc-dev libarchive-dev uthash-dev

      - name: Clone PRoot
        run: git clone https://github.com/proot-me/proot -b master

      - name: Build PRoot and CARE
        run: |
          cd proot/src

          # Detect target triplet
          case "${{ matrix.abi }}" in
            arm64-v8a)
              TARGET=aarch64-linux-android
              API=24
              ;;
            x86_64)
              TARGET=x86_64-linux-android
              API=24
              ;;
          esac

          # Find NDK clang
          NDK_DIR=$(ls -d $ANDROID_SDK_ROOT/ndk/* | sort -V | tail -n1)
          TOOLCHAIN=$NDK_DIR/toolchains/llvm/prebuilt/linux-x86_64/bin
          export CROSS_COMPILE=${TOOLCHAIN}/${TARGET}${API}-

          # Make
          make loader.elf loader-m32.elf build.h
          make proot care

          # Copy executables to dist folder
          mkdir -p ../../dist/${{ matrix.abi }}
          cp proot ../../dist/${{ matrix.abi }}/
          cp care ../../dist/${{ matrix.abi }}/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proot-android-${{ matrix.abi }}
          path: dist/${{ matrix.abi }}/
