name: Build PRoot for Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [arm64-v8a, x86_64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Android NDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'ndk;28.2.13676358'

      - name: Set up build tools
        run: sudo apt-get update && sudo apt-get install -y make git

      - name: Clone PRoot
        run: git clone https://github.com/proot-me/proot -b master

      - name: Build PRoot .so
        run: |
          cd proot/src
          
          # Choose toolchain and architecture
          case "${{ matrix.abi }}" in
            armeabi-v7a)
              TARGET=armv7a-linux-androideabi
              ;;
            arm64-v8a)
              TARGET=aarch64-linux-android
              ;;
            x86)
              TARGET=i686-linux-android
              ;;
            x86_64)
              TARGET=x86_64-linux-android
              ;;
          esac
          
          NDK_DIR=$(find "$ANDROID_SDK_ROOT/ndk" -maxdepth 1 -type d | tail -n +2)
          TOOLCHAIN="$NDK_DIR/toolchains/llvm/prebuilt/linux-x86_64/bin"

          CC=$TOOLCHAIN/${TARGET}24-clang
          CFLAGS="-fPIC -O2 -DANDROID"
          LDFLAGS="-shared"

          echo "Compiling for $TARGET"

          # Compile to .o
          $CC $CFLAGS -c proot.c -o proot.o
          $CC $CFLAGS -c loader.c -o loader.o
          $CC $CFLAGS -c loader-m32.c -o loader-m32.o
          $CC $CFLAGS -c care.c -o care.o

          # Link to .so
          $CC $LDFLAGS -o libproot.so proot.o loader.o loader-m32.o care.o

          mkdir -p ../../dist/${{ matrix.abi }}
          mv libproot.so ../../dist/${{ matrix.abi }}/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proot-android-${{ matrix.abi }}
          path: dist/${{ matrix.abi }}/libproot.so
