name: Build PRoot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [amd64, arm64]  # used by docker create --platform
        distro: ["ubuntu:latest"]

    container:
      image: ${{ matrix.distro }}
      options: --platform linux/${{ matrix.arch }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run in Docker
        run: |
          sh scripts/deps-install-$(echo '${{ matrix.distro }}' | cut -d':' -f1).sh
          sh scripts/build-proot.sh"

      - name: Upload executables
        uses: actions/upload-artifact@v4
        with:
          name: proot-${{ matrix.arch }}
          path: proot/dist/
