name: Build PRoot for Android

on:
  workflow_dispatch:

env:
  PREFIX: ./dependencies/install
  DWNLD: ./dependencies/download
jobs:
  build:
    strategy:
      matrix:
        arch: [aarch64, x86_64]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r28c

      - name: Download dependencies
        run: |
          sudo apt-get install -y autoconf automake libtool pkg-config

          mkdir -p ${{ env.PREFIX }}
          mkdir -p ${{ env.DWNLD }}
          cd ${{ env.DWNLD }}

          # libarchive
          git clone https://github.com/libarchive/libarchive.git -b v3.8.1
          git clone https://gitlab.gnome.org/GNOME/libxml2 

          # talloc
          curl -LO https://www.samba.org/ftp/talloc/talloc-2.4.3.tar.gz
          tar xzf talloc-2.4.3.tar.gz
          mv talloc-2.4.3 talloc
          # uthash
          git clone https://github.com/troydhanson/uthash.git -b v2.3.0

          git clone https://github.com/proot-me/proot.git

      - name: Build dependencies
        env:
          ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
          ARCH: ${{ matrix.arch }}
          PREFIX: ${{ env.PREFIX }}
          DWNLD: ${{ env.DWNLD }}
        run: |

          export TOOLCHAIN=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64
          export TARGET=$ARCH-linux-android
          export API=24

          export AR=$TOOLCHAIN/bin/llvm-ar
          export CC="$TOOLCHAIN/bin/clang --target=$TARGET$API"
          export AS=$CC
          export CXX="$TOOLCHAIN/bin/clang++ --target=$TARGET$API"
          export LD=$TOOLCHAIN/bin/ld
          export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
          export STRIP=$TOOLCHAIN/bin/llvm-strip

          export DWNLD=$(realpath $DWNLD)
          export PREFIX=$(realpath $PREFIX)

          # libarchive
          cd $DWNLD/libarchive
          sh ./build/autogen.sh
          ./configure --host=$TARGET --prefix=$PREFIX \
          --disable-lzma \
          --disable-bz2 \
          --disable-lz4 \
          --disable-zstd \
          --disable-xattr \
          --disable-acl \
          --disable-iconv \
          --disable-expat \
          --disable-nettle \
          --disable-openssl \
          --disable-xml2 \
          --disable-cng \
          --disable-xar \
          --disable-cpio \
          --disable-shared \
          --enable-static 
          make
          make install
          cd ..

          # talloc
          cd $DWNLD/talloc
          ./configure --host $TARGET --prefix=$PREFIX
          make
          make install

          # uthash
          cd $DWNLD/uthash
          mkdir -p $PREFIX/include/
          cp -r src/* $PREFIX/include/

          cd $DWNLD/proot/src

          # Symlink tools
          ln -sf ${TOOLCHAIN}/${TARGET}${API}-clang  ${TOOLCHAIN}/${TARGET}${API}-gcc
          ln -sf ${TOOLCHAIN}/${TARGET}${API}-clang++ ${TOOLCHAIN}/${TARGET}${API}-g++
          ln -sf ${TOOLCHAIN}/llvm-strip ${TOOLCHAIN}/${TARGET}${API}-strip
          export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH

          export CFLAGS="-I$PREFIX/include"
          export LDFLAGS="-L$PREFIX/lib"

          make loader.elf loader-m32.elf build.h
          make proot care

          mkdir -p ../../dist/$ARCH
          cp proot ../../dist/$ARCH/
          cp care ../../dist/$ARCH/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proot-android-${{ matrix.arch }}
          path: dist/${{ matrix.arch }}/
